;A PROGRAM TO EXCHANGE OF TWO VARIABLES

.MODEL SMALL 

.STACK 100H

.DATA ; ALL VARIABLES WILL GO HERE 
    MYCHAR1 DB 'A'
    MYCHAR2 DB 'Z'   
    MSG1 DB 'VALUE IN FIRST MYCHAR1 $'
    MSG2 DB 'VALUE IN FIRST MYCHAR2 $'
    
    CR EQU 0DH    ;CONSTANT
    NL EQU 0AH 
    
.CODE 
MAIN PROC 
    ;LOAD THE DATA SEGMENT - IF YOU HAVE VARIABLES 
    MOV AX,@DATA ;ADDRESS OF DATA SEGMENT OR ZONE OF MEMORY WHERE VARIABLES ARE KEPT
    MOV DS,AX ;MUST BE LOADED INTO DATA SEGMENT REGISTER   
    
    ;SHOW MSG
    MOV AH,9
    LEA DX,MSG1 ;LOAD STRING MSG IN DX
    INT 21H
    ;show mychar1
    MOV AH,2 ; PRINT SINGLE CHARACTER
    MOV DL,MYCHAR1
    INT 21H 
    
    ;NEWLINE 
    MOV AH,2
    MOV DL,CR ;CARRIAGE RETURN <START OF LINE IN LEFT>
    INT 21H
    MOV DL,NL ;LINE PRINT  (NEW LINE)
    INT 21H
    
     ;SHOW 2ND MSG
    MOV AH,9
    LEA DX,MSG2 ;LOAD STRING MSG IN DX
    INT 21H
    ;show mychar2
    MOV AH,2 ; PRINT SINGLE CHARACTER
    MOV DL,MYCHAR2
    INT 21H  
    
    ;EXCHANGE TWO VARIABLES
     MOV BL,MYCHAR1 ;BL = A
     XCHG BL,MYCHAR2 ;BL =Z AND MYCHAR2 = A
     MOV MYCHAR1,BL   ;MYCHAR1 = Z   
     
     
      ;NEWLINE 
    MOV AH,2
    MOV DL,CR ;CARRIAGE RETURN <START OF LINE IN LEFT>
    INT 21H
    MOV DL,NL ;LINE PRINT  (NEW LINE)
    INT 21H
     
     ;SHOW MSG AGAIN
    MOV AH,9
    LEA DX,MSG1 ;LOAD STRING MSG IN DX
    INT 21H
    ;show mychar1
    MOV AH,2 ; PRINT SINGLE CHARACTER
    MOV DL,MYCHAR1
    INT 21H 
    
    ;NEWLINE 
    MOV AH,2
    MOV DL,CR ;CARRIAGE RETURN <START OF LINE IN LEFT>
    INT 21H
    MOV DL,NL ;LINE PRINT  (NEW LINE)
    INT 21H
    
     ;SHOW 2ND MSG
    MOV AH,9
    LEA DX,MSG2 ;LOAD STRING MSG IN DX
    INT 21H
    ;show mychar2
    MOV AH,2 ; PRINT SINGLE CHARACTER
    MOV DL,MYCHAR2
    INT 21H  
    
    
    ;WE HAVE TO RETURN CONTREOL TO DOS 
    MOV AH,4CH
    INT 21H ;CALL TO DOS  
    
    MAIN ENDP ;END OF MAIN PROCEDURE  
    ;CAN LOAD OTHER PROCEDURES 
    
END MAIN ;END OF PROGRAM
    